apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: openig
  namespace: mynamespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: openig
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
