kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: userstore-pv-claim
  namespace: roylab
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi