kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: userstore-pv-claim
  namespace: ultids
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi