apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
  namespace: mynamespace
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: fr-simple-app
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: fr-simple-app-ssl
    port: 8444
    protocol: TCP
    targetPort: 8444
  selector:
    app: httpd
