apiVersion: v1
kind: Service
metadata:
  name: gatling-svc
  namespace: roylab
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: gatling
